# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
app_name: gpii-binder

git_repository: https://github.com/the-t-in-rtf/gpii-binder.git

email: tony@raisingthefloor.org

env_runtime: linux-desktop

app_start_service: false

software_stack: nodejs

software_stack_version: lts

setup:
  - npm install

commands:
  - npm test

publishers:
  - cobertura:
      report-file: "coverage/cobertura-coverage.xml"